version: "3.8"
services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_TTL_MS=${JWT_ACCESS_TOKEN_TTL_MS}

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - back
    # environment:
    #   - SSL_CERTIFICATE=${SSL_CERTIFICATE}
    #   - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY}
    # volumes:
    #   - ${SSL_CERTIFICATE}:${SSL_CERTIFICATE}:ro
    #   - ${SSL_CERTIFICATE_KEY}:${SSL_CERTIFICATE_KEY}:ro
